In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries loaded")

Libraries loaded

In [3]:
df = pd.read_csv("../data/train.csv")
print(df.shape)
print(df.columns.tolist())
df.head()

(8523, 12)
['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility', 'Item_Type', 'Item_MRP', 'Outlet_Identifier', 'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type', 'Item_Outlet_Sales']

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [5]:
df['Item_Fat_Content'].value_counts()

Item_Fat_Content
Low Fat    5089
Regular    2889
LF          316
reg         117
low fat     112
Name: count, dtype: int64

In [6]:
df['Item_Fat_Content'] = df['Item_Fat_Content'].replace({
    'low fat': 'Low Fat',
    'LF': 'Low Fat',
    'reg': 'Regular'
})
print(df['Item_Fat_Content'].value_counts())

Item_Fat_Content
Low Fat    5517
Regular    3006
Name: count, dtype: int64

In [7]:
print(df['Item_Visibility'].describe())
print("---")
print((df['Item_Visibility'] == 0).sum())

count    8523.000000
mean        0.066132
std         0.051598
min         0.000000
25%         0.026989
50%         0.053931
75%         0.094585
max         0.328391
Name: Item_Visibility, dtype: float64
---
526

In [8]:
df.describe()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,7060.000000,8523.000000,8523.000000,8523.000000,8523.000000
mean,12.857645,0.066132,140.992782,1997.831867,2181.288914
std,4.643456,0.051598,62.275067,8.371760,1706.499616
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,8.773750,0.026989,93.826500,1987.000000,834.247400
50%,12.600000,0.053931,143.012800,1999.000000,1794.331000
75%,16.850000,0.094585,185.643700,2004.000000,3101.296400
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [9]:
print(df['Item_Type'].value_counts())
print("---")
print(df['Outlet_Size'].value_counts())
print("---")
print(df['Outlet_Location_Type'].value_counts())
print("---")
print(df['Outlet_Type'].value_counts())

Item_Type
Fruits and Vegetables    1232
Snack Foods              1200
Household                 910
Frozen Foods              856
Dairy                     682
Canned                    649
Baking Goods              648
Health and Hygiene        520
Soft Drinks               445
Meat                      425
Breads                    251
Hard Drinks               214
Others                    169
Starchy Foods             148
Breakfast                 110
Seafood                    64
Name: count, dtype: int64
---
Outlet_Size
Medium    2793
Small     2388
High       932
Name: count, dtype: int64
---
Outlet_Location_Type
Tier 3    3350
Tier 2    2785
Tier 1    2388
Name: count, dtype: int64
---
Outlet_Type
Supermarket Type1    5577
Grocery Store        1083
Supermarket Type3     935
Supermarket Type2     928
Name: count, dtype: int64

In [10]:
print(df['Outlet_Identifier'].nunique())
print(df['Item_Identifier'].nunique())

10
1559

In [11]:
df.groupby('Outlet_Identifier')['Item_Outlet_Sales'].mean().sort_values(ascending=False)

Outlet_Identifier
OUT027    3694.038558
OUT035    2438.841866
OUT049    2348.354635
OUT017    2340.675263
OUT013    2298.995256
OUT046    2277.844267
OUT045    2192.384798
OUT018    1995.498739
OUT019     340.329723
OUT010     339.351662
Name: Item_Outlet_Sales, dtype: float64

In [12]:
df[df['Outlet_Identifier'].isin(['OUT019', 'OUT010'])][['Outlet_Identifier', 'Outlet_Type', 'Outlet_Size', 'Outlet_Location_Type']].drop_duplicates()

   Outlet_Identifier    Outlet_Type Outlet_Size Outlet_Location_Type
3             OUT010  Grocery Store         NaN               Tier 3
23            OUT019  Grocery Store       Small               Tier 1

In [13]:
df.groupby('Outlet_Type')['Item_Outlet_Sales'].mean().sort_values(ascending=False)

Outlet_Type
Supermarket Type3    3694.038558
Supermarket Type1    2316.181148
Supermarket Type2    1995.498739
Grocery Store         339.828500
Name: Item_Outlet_Sales, dtype: float64

In [14]:
print(df.groupby('Outlet_Size')['Item_Outlet_Sales'].mean())
print("---")
print(df.groupby('Outlet_Establishment_Year')['Item_Outlet_Sales'].mean())

Outlet_Size
High      2298.995256
Medium    2681.603542
Small     1912.149161
Name: Item_Outlet_Sales, dtype: float64
---
Outlet_Establishment_Year
1985    2483.677474
1987    2298.995256
1997    2277.844267
1998     339.351662
1999    2348.354635
2002    2192.384798
2004    2438.841866
2007    2340.675263
2009    1995.498739
Name: Item_Outlet_Sales, dtype: float64

In [15]:
df[df['Outlet_Establishment_Year'] == 1998]['Outlet_Identifier'].unique()

array(['OUT010'], dtype=object)

In [16]:
print(df.groupby('Item_Type')['Item_Outlet_Sales'].mean().sort_values(ascending=False))
print("---")
print(df['Item_MRP'].corr(df['Item_Outlet_Sales']))
print("---")
print(df['Item_Weight'].corr(df['Item_Outlet_Sales']))

Item_Type
Starchy Foods            2374.332773
Seafood                  2326.065928
Fruits and Vegetables    2289.009592
Snack Foods              2277.321739
Household                2258.784300
Dairy                    2232.542597
Canned                   2225.194904
Breads                   2204.132226
Meat                     2158.977911
Hard Drinks              2139.221622
Frozen Foods             2132.867744
Breakfast                2111.808651
Health and Hygiene       2010.000265
Soft Drinks              2006.511735
Baking Goods             1952.971207
Others                   1926.139702
Name: Item_Outlet_Sales, dtype: float64
---
0.5675744466569194
---
0.014122739280056463

In [17]:
print(df['Item_Visibility'].corr(df['Item_Outlet_Sales']))
print("---")
print(df.groupby('Item_Fat_Content')['Item_Outlet_Sales'].mean())

-0.1286246122207703
---
Item_Fat_Content
Low Fat    2157.711534
Regular    2224.561170
Name: Item_Outlet_Sales, dtype: float64

In [18]:
from scipy.stats import f_oneway

categorical_features = ['Item_Fat_Content', 'Item_Type', 'Outlet_Identifier',
                         'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']

results = []
for feature in categorical_features:
    groups = [df[df[feature] == val]['Item_Outlet_Sales'] for val in df[feature].dropna().unique()]
    f_stat, p_value = f_oneway(*groups)
    results.append((feature, p_value))

results.sort(key=lambda x: x[1])
for feature, p in results:
    significant = "KEEP" if p < 0.05 else "DROP"
    print(f"{feature:25s} p-value = {p:.10f}  {significant}")

Outlet_Identifier         p-value = 0.0000000000  KEEP
Outlet_Type               p-value = 0.0000000000  KEEP
Outlet_Size               p-value = 0.0000000000  KEEP
Outlet_Location_Type      p-value = 0.0000000000  KEEP
Item_Type                 p-value = 0.0003884399  KEEP
Item_Fat_Content          p-value = 0.0839891697  DROP

In [19]:
df[df['Outlet_Type'] == 'Supermarket Type1'].groupby('Outlet_Identifier')['Item_Outlet_Sales'].mean()

Outlet_Identifier
OUT013    2298.995256
OUT017    2340.675263
OUT035    2438.841866
OUT045    2192.384798
OUT046    2277.844267
OUT049    2348.354635
Name: Item_Outlet_Sales, dtype: float64

In [20]:
df[df['Outlet_Size'].isna()]['Outlet_Type'].value_counts()

Outlet_Type
Supermarket Type1    1855
Grocery Store         555
Name: count, dtype: int64

In [21]:
df[df['Outlet_Type'] == 'Grocery Store']['Outlet_Size'].value_counts()
print("---")
df[df['Outlet_Type'] == 'Supermarket Type1']['Outlet_Size'].value_counts()

---

Outlet_Size
Small     1860
High       932
Medium     930
Name: count, dtype: int64

In [22]:
print("Grocery Store:")
print(df[df['Outlet_Type'] == 'Grocery Store']['Outlet_Size'].value_counts())
print("---")
print("Supermarket Type1:")
print(df[df['Outlet_Type'] == 'Supermarket Type1']['Outlet_Size'].value_counts())

Grocery Store:
Outlet_Size
Small    528
Name: count, dtype: int64
---
Supermarket Type1:
Outlet_Size
Small     1860
High       932
Medium     930
Name: count, dtype: int64

In [23]:
df.loc[(df['Outlet_Size'].isna()) & (df['Outlet_Type'] == 'Grocery Store'), 'Outlet_Size'] = 'Small'
df.loc[df['Outlet_Size'].isna(), 'Outlet_Size'] = 'Unknown'

print(df['Outlet_Size'].value_counts())
print("---")
print(df['Outlet_Size'].isna().sum())

Outlet_Size
Small      2943
Medium     2793
Unknown    1855
High        932
Name: count, dtype: int64
---
0

In [24]:
X = df[['Item_MRP', 'Outlet_Type', 'Outlet_Size', 'Outlet_Location_Type', 'Item_Type']]
y = df['Item_Outlet_Sales']

print(X.shape)
print(y.shape)

(8523, 5)
(8523,)

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print(f"Training set: {X_train.shape}")
print(f"Testing set:  {X_test.shape}")

Training set: (6818, 5)
Testing set:  (1705, 5)

In [26]:
print(X_train['Outlet_Type'].nunique())
print(X_train['Outlet_Size'].nunique())
print(X_train['Outlet_Location_Type'].nunique())
print(X_train['Item_Type'].nunique())

4
4
3
16

In [27]:
encoding_map = y_train.groupby(X_train['Item_Type']).mean()

X_train = X_train.copy()
X_train['Item_Type_encoded'] = X_train['Item_Type'].map(encoding_map)

X_test = X_test.copy()
X_test['Item_Type_encoded'] = X_test['Item_Type'].map(encoding_map)

X_train = X_train.drop('Item_Type', axis=1)
X_test = X_test.drop('Item_Type', axis=1)

print(X_train.head())

      Item_MRP        Outlet_Type Outlet_Size Outlet_Location_Type  \
549   171.3448  Supermarket Type1      Medium               Tier 1
7757  170.5422  Supermarket Type1     Unknown               Tier 2
764   111.7202  Supermarket Type1       Small               Tier 1
6867   41.6138  Supermarket Type1     Unknown               Tier 2
2716  155.5630  Supermarket Type1       Small               Tier 1

      Item_Type_encoded
549         2321.843277
7757        2261.702912
764         2191.256377
6867        2321.843277
2716        2295.101739

In [28]:
X_train = pd.get_dummies(X_train, columns=['Outlet_Type', 'Outlet_Size', 'Outlet_Location_Type'])
X_test = pd.get_dummies(X_test, columns=['Outlet_Type', 'Outlet_Size', 'Outlet_Location_Type'])

X_train = X_train.astype({col: int for col in X_train.columns if X_train[col].dtype == 'bool'})
X_test = X_test.astype({col: int for col in X_test.columns if X_test[col].dtype == 'bool'})

print(X_train.shape)
print(X_train.head())

(6818, 13)
      Item_MRP  Item_Type_encoded  Outlet_Type_Grocery Store  \
549   171.3448        2321.843277                          0
7757  170.5422        2261.702912                          0
764   111.7202        2191.256377                          0
6867   41.6138        2321.843277                          0
2716  155.5630        2295.101739                          0

      Outlet_Type_Supermarket Type1  Outlet_Type_Supermarket Type2  \
549                               1                              0
7757                              1                              0
764                               1                              0
6867                              1                              0
2716                              1                              0

      Outlet_Type_Supermarket Type3  Outlet_Size_High  Outlet_Size_Medium  \
549                               0                 0                   1
7757                              0                 0                   0
764                               0                 0                   0
6867                              0                 0                   0
2716                              0                 0                   0

      Outlet_Size_Small  Outlet_Size_Unknown  Outlet_Location_Type_Tier 1  \
549                   0                    0                            1
7757                  0                    1                            0
764                   1                    0                            1
6867                  0                    1                            0
2716                  1                    0                            1

      Outlet_Location_Type_Tier 2  Outlet_Location_Type_Tier 3
549                             0                            0
7757                            1                            0
764                             0                            0
6867                            1                            0
2716                            0                            0

In [29]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

model_lr = LinearRegression()
model_lr.fit(X_train, y_train)

y_pred_lr = model_lr.predict(X_test)

mae = mean_absolute_error(y_test, y_pred_lr)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_lr))
r2 = r2_score(y_test, y_pred_lr)

print(f"MAE:  {mae:.3f}")
print(f"RMSE: {rmse:.3f}")
print(f"R²:   {r2:.3f}")

MAE:  791.441
RMSE: 1068.607
R²:   0.580

In [30]:
from sklearn.ensemble import RandomForestRegressor

model_rf = RandomForestRegressor(random_state=42, n_estimators=100, max_depth=8, min_samples_leaf=10)
model_rf.fit(X_train, y_train)

y_train_pred_rf = model_rf.predict(X_train)
y_test_pred_rf = model_rf.predict(X_test)

print(f"Training R²: {r2_score(y_train, y_train_pred_rf):.3f}")
print(f"Test R²:     {r2_score(y_test, y_test_pred_rf):.3f}")
print("---")
print(f"MAE:  {mean_absolute_error(y_test, y_test_pred_rf):.3f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_test, y_test_pred_rf)):.3f}")

Training R²: 0.635
Test R²:     0.611
---
MAE:  718.019
RMSE: 1028.200

In [31]:
from sklearn.ensemble import GradientBoostingRegressor

model_gb = GradientBoostingRegressor(random_state=42, n_estimators=100, max_depth=3, learning_rate=0.1)
model_gb.fit(X_train, y_train)

y_train_pred_gb = model_gb.predict(X_train)
y_test_pred_gb = model_gb.predict(X_test)

print(f"Training R²: {r2_score(y_train, y_train_pred_gb):.3f}")
print(f"Test R²:     {r2_score(y_test, y_test_pred_gb):.3f}")
print("---")
print(f"MAE:  {mean_absolute_error(y_test, y_test_pred_gb):.3f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_test, y_test_pred_gb)):.3f}")

Training R²: 0.630
Test R²:     0.603
---
MAE:  721.993
RMSE: 1039.216

In [32]:
importances = pd.Series(model_rf.feature_importances_, index=X_train.columns).sort_values(ascending=False)
print(importances)

Item_MRP                         0.556459
Outlet_Type_Grocery Store        0.300726
Outlet_Type_Supermarket Type3    0.116624
Item_Type_encoded                0.014702
Outlet_Type_Supermarket Type1    0.003455
Outlet_Type_Supermarket Type2    0.002369
Outlet_Location_Type_Tier 3      0.001174
Outlet_Size_Small                0.001020
Outlet_Size_High                 0.000769
Outlet_Location_Type_Tier 1      0.000741
Outlet_Location_Type_Tier 2      0.000671
Outlet_Size_Unknown              0.000667
Outlet_Size_Medium               0.000623
dtype: float64